# Generated by Django 6.1.1 on 2026-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_handle', models.CharField(blank=True, max_length=30)),
                ('business_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('vendor_category', models.CharField(choices=[('Arts, Prints & Stickers', 'Arts, Prints & Stickers'), ('Beauty & Cosmetics', 'Beauty & Cosmetics'), ('Ceramics / Glass', 'Ceramics / Glass'), ('Clothing Brand', 'Clothing Brand'), ('Crotchet, Sewing, Quilt Goods', 'Crotchet, Sewing, Quilt Goods'), ('Cultural Collectibles', 'Cultural Collectibles'), ('Experience', 'Experience'), ('Homeware', 'Homeware'), ('Jewelry', 'Jewelry'), ('Leatherwork', 'Leatherwork'), ('Music / Vinyl', 'Music / Vinyl'), ('NYC Merch', 'NYC Merch'), ('Pets Accessories', 'Pets Accessories'), ('Photography', 'Photography'), ('Plants', 'Plants'), ('Soaps / Candles and Perfume', 'Soaps / Candles and Perfume'), ('Stationery', 'Stationery'), ('Unique Things', 'Unique Things'), ('Vintage Clothing', 'Vintage Clothing'), ('Vintage General', 'Vintage General'), ('Vintage Homeware', 'Vintage Homeware'), ('Vintage Jewelry', 'Vintage Jewelry'), ('Vintage Upcycled', 'Vintage Upcycled')], max_length=100)),
                ('lead_source', models.CharField(choices=[('Instagram', 'Instagram'), ('Email', 'Email'), ('Meta ads', 'Meta ads'), ('Shopify form', 'Shopify form'), ('Google form', 'Google form')], max_length=30)),
                ('interest_level', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=4)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
