# Generated by Django 6.1.1 on 2026-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlead',
            name='added_to_market_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='agreed_weekend_dates',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='application_challenges',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='available_to_chat',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Reschedule requested', 'Reschedule requested')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='business_commitment',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Hobbyist', 'Hobbyist')], max_length=20),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='call_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('Connected', 'Connected'), ('Left Voicemail', 'Left Voicemail'), ('Busy', 'Busy'), ('Rescheduled', 'Rescheduled')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='currently_does_markets',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='followup_status',
            field=models.CharField(blank=True, choices=[('Closed - Confirmed', 'Closed - Confirmed'), ('Follow-up Needed', 'Follow-up Needed'), ('Unqualified', 'Unqualified'), ('Lost', 'Lost')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='identity_verified',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='information_packet_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='insurance_setup_walked_through',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='insurance_status',
            field=models.CharField(blank=True, choices=[('Have active policy', 'Have active policy'), ('Need guidance', 'Need guidance'), ("Don't have", "Don't have")], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='location_pain_points',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='long_term_outlook',
            field=models.CharField(blank=True, choices=[('One-off', 'One-off'), ('Seasonal', 'Seasonal'), ('Long-term recurring anchor vendor', 'Long-term recurring anchor vendor')], max_length=40),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='markets_and_frequency',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='offer_concerns',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='offer_interest',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Hesitant'), (2, 'Hesitant'), (3, 'Neutral'), (4, 'Excited'), (5, 'Extremely Excited')], null=True),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='onboarding_dates_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='primary_goals',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('LLC', 'LLC'), ('Sole Prop', 'Sole Prop'), ('In Progress', 'In Progress'), ('None', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='revenue_consistency',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='team_details',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='trial_commitment',
            field=models.CharField(blank=True, choices=[('Agreed', 'Agreed'), ('Under Consideration', 'Under Consideration'), ('Declined', 'Declined')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='trial_term_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='vendor_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
