# Generated by Django 6.1.1 on 2026-09-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vendorlead_added_to_market_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlead',
            name='application_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='coi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='info_packet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='vendor_contract',
            field=models.BooleanField(default=False),
        ),
    ]
