# Generated by Django 6.1.1 on 2026-09-29 20:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vendorlead_application_decision_vendorlead_coi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('due_date', models.DateField()),
                ('payment_instructions', models.TextField(max_length=2000)),
                ('personal_message', models.TextField(blank=True, max_length=5000)),
                ('weekend_dates', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_invoice', to='api.vendorlead')),
            ],
        ),
    ]
