# Generated by Django 6.1.1 on 2026-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_approvalinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalinvoice',
            name='invoice_link',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
