# Generated by Django 6.1.1 on 2026-09-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_approvalinvoice_invoice_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='approvalinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0), ('amount_paid__lte', models.F('amount'))), name='approval_invoice_valid_amount_paid'),
        ),
    ]
