# Generated by Django 6.1.1 on 2026-09-29 22:57

import django.db.models.deletion
from django.db import migrations, models

MARKET_WEEKENDS = [
    'October 10 & 11', 'October 17 & 18', 'October 24 & 25',
    'October 31 & November 1', 'November 7 & 8', 'November 14 & 15',
    'November 21 & 22', 'November 28 & 29', 'December 5 & 6',
    'December 12 & 13', 'December 19 & 20', 'December 26 & 27',
]


def create_weekend_bookings(apps, schema_editor):
    ApprovalInvoice = apps.get_model('api', 'ApprovalInvoice')
    MarketWeekendBooking = apps.get_model('api', 'MarketWeekendBooking')
    for invoice in ApprovalInvoice.objects.select_related('lead').all():
        selected = [
            weekend for weekend in MARKET_WEEKENDS
            if weekend in {value.strip() for value in invoice.weekend_dates.split(' | ') if value.strip()}
        ]
        for index, weekend in enumerate(selected):
            MarketWeekendBooking.objects.create(
                lead_id=invoice.lead_id,
                invoice_id=invoice.pk,
                weekend=weekend,
                amount_paid=invoice.amount_paid if index == 0 else 0,
            )


def restore_invoice_payments(apps, schema_editor):
    ApprovalInvoice = apps.get_model('api', 'ApprovalInvoice')
    MarketWeekendBooking = apps.get_model('api', 'MarketWeekendBooking')
    for invoice in ApprovalInvoice.objects.all():
        invoice.amount_paid = sum(
            booking.amount_paid for booking in MarketWeekendBooking.objects.filter(invoice_id=invoice.pk)
        )
        invoice.save(update_fields=['amount_paid'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_approvalinvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketWeekendBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend', models.CharField(choices=[('October 10 & 11', 'October 10 & 11'), ('October 17 & 18', 'October 17 & 18'), ('October 24 & 25', 'October 24 & 25'), ('October 31 & November 1', 'October 31 & November 1'), ('November 7 & 8', 'November 7 & 8'), ('November 14 & 15', 'November 14 & 15'), ('November 21 & 22', 'November 21 & 22'), ('November 28 & 29', 'November 28 & 29'), ('December 5 & 6', 'December 5 & 6'), ('December 12 & 13', 'December 12 & 13'), ('December 19 & 20', 'December 19 & 20'), ('December 26 & 27', 'December 26 & 27')], max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['weekend', 'lead__business_name', 'lead_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='approvalinvoice',
            name='approval_invoice_valid_amount_paid',
        ),
        migrations.AddField(
            model_name='marketweekendbooking',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_bookings', to='api.approvalinvoice'),
        ),
        migrations.AddField(
            model_name='marketweekendbooking',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_bookings', to='api.vendorlead'),
        ),
        migrations.RunPython(create_weekend_bookings, restore_invoice_payments),
        migrations.RemoveField(
            model_name='approvalinvoice',
            name='amount_paid',
        ),
        migrations.AddConstraint(
            model_name='marketweekendbooking',
            constraint=models.UniqueConstraint(fields=('lead', 'weekend'), name='unique_vendor_market_weekend'),
        ),
        migrations.AddConstraint(
            model_name='marketweekendbooking',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='market_booking_nonnegative_paid'),
        ),
    ]
