# Generated by Django 6.1.1 on 2026-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_marketweekendbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlead',
            name='funnel_stage',
            field=models.CharField(choices=[('new_application', 'New application'), ('vendor', 'Vendor')], db_index=True, default='vendor', max_length=20),
        ),
    ]
