# Generated by Django 6.1.1 on 2026-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vendorlead_funnel_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlead',
            name='lead_source',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Email', 'Email'), ('Meta ads', 'Meta ads'), ('Shopify form', 'Shopify form'), ('Google form', 'Google form'), ('Google Sheets', 'Google Sheets')], max_length=30),
        ),
    ]
