# Generated by Django 6.1.1 on 2026-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_vendorlead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlead',
            name='agreed_pricing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('Single Weekend', 'Single Weekend'), ('Multi-Weekend Package', 'Multi-Weekend Package'), ('Recurring Seasonal Vendor', 'Recurring Seasonal Vendor')], max_length=40),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='brand_description_aesthetic',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='equipment_needs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='historical_vendor_feedback',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='lead_qualification',
            field=models.CharField(blank=True, choices=[('Qualified & Ready', 'Qualified & Ready'), ('Needs Follow-Up', 'Needs Follow-Up'), ('Deferred', 'Deferred'), ('Not a Fit', 'Not a Fit')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='next_action_required',
            field=models.CharField(blank=True, choices=[('Send Shopify Draft Invoice', 'Send Shopify Draft Invoice'), ('Send Follow-Up Email', 'Send Follow-Up Email'), ('Schedule Second Call', 'Schedule Second Call'), ('Pass to Market Ops', 'Pass to Market Ops')], max_length=40),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='objections_concerns',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='operational_placement_notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='previous_market_experience',
            field=models.CharField(blank=True, choices=[('First-Time Vendor', 'First-Time Vendor'), ('Experienced Pop-Up Vendor', 'Experienced Pop-Up Vendor'), ('Returning Good Flea Vendor', 'Returning Good Flea Vendor')], max_length=40),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='price_point_range',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='primary_vendor_goal',
            field=models.CharField(blank=True, choices=[('High Sales Volume', 'High Sales Volume'), ('Brand Awareness', 'Brand Awareness'), ('Product Testing', 'Product Testing'), ('Content Creation', 'Content Creation')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Apparel/Fashion', 'Apparel/Fashion'), ('Jewelry & Accessories', 'Jewelry & Accessories'), ('Beauty & Wellness', 'Beauty & Wellness'), ('Home Goods', 'Home Goods'), ('Vintage/Thrift', 'Vintage/Thrift'), ('Art & Craft', 'Art & Craft'), ('Pre-Packaged Food', 'Pre-Packaged Food'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='readiness_level',
            field=models.CharField(blank=True, choices=[('Ready Now', 'Ready Now'), ('Needs 1–2 Weeks', 'Needs 1–2 Weeks'), ('Exploring Options', 'Exploring Options')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='target_market_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='vendor_pipeline_stage',
            field=models.CharField(blank=True, choices=[('Call Completed -> Pending Invoice', 'Call Completed -> Pending Invoice'), ('Invoice Sent -> Awaiting Payment', 'Invoice Sent -> Awaiting Payment'), ('Booked & Paid', 'Booked & Paid'), ('Closed / Rejected', 'Closed / Rejected')], max_length=50),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='website_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
