# Generated by Django 6.1.1 on 2026-10-06 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vendor_call_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='per weekend', max_length=50)),
                ('has_inventory', models.BooleanField(default=False)),
                ('total_inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_vendor', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['market', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoothVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in feet', null=True)),
                ('depth', models.PositiveIntegerField(blank=True, help_text='Depth in feet', null=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['market', 'price'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('not_booked', 'Not Booked'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('attended', 'Attended'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], db_index=True, default='reserved', max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_ons', models.ManyToManyField(blank=True, related_name='bookings', to='api.addon')),
                ('booth_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.boothvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday_status', models.CharField(choices=[('expected', 'Expected'), ('checked_in', 'Checked In'), ('absent', 'Absent'), ('no_show', 'No-show'), ('excused', 'Excused')], default='expected', max_length=20)),
                ('sunday_status', models.CharField(choices=[('expected', 'Expected'), ('checked_in', 'Checked In'), ('absent', 'Absent'), ('no_show', 'No-show'), ('excused', 'Excused')], default='expected', max_length=20)),
                ('saturday_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('sunday_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='api.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(db_index=True, default=False)),
                ('booth_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='api.boothvariant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHoldAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.addon')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryhold')),
            ],
            options={
                'unique_together': {('hold', 'add_on')},
            },
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='add_ons',
            field=models.ManyToManyField(related_name='holds', through='api.InventoryHoldAddOn', to='api.addon'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('not_invoiced', 'Not Invoiced'), ('invoice_draft', 'Invoice Draft'), ('invoice_sent', 'Invoice Sent'), ('payment_pending', 'Payment Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='invoice_draft', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('hold_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('payment_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('external_payment_id', models.CharField(blank=True, max_length=255)),
                ('webhook_event_id', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField(blank=True)),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.boothvariant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_hold', to='api.invoice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='api.invoice'),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('add_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='api.addon')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.invoice')),
            ],
            options={
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('saturday_date', models.DateField()),
                ('sunday_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('booking_opening_date', models.DateField()),
                ('booking_closing_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('total_booth_capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['saturday_date'],
                'indexes': [models.Index(fields=['status', 'saturday_date'], name='api_marketp_status_9b4e8b_idx')],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.marketproduct'),
        ),
        migrations.AddField(
            model_name='boothvariant',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_variants', to='api.marketproduct'),
        ),
        migrations.AddField(
            model_name='booking',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.marketproduct'),
        ),
        migrations.AddField(
            model_name='addon',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='api.marketproduct'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('check', 'Check'), ('stripe', 'Stripe'), ('other', 'Other')], max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('internal_note', models.TextField(blank=True, max_length=1000)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('contact_needed', 'Contact Needed'), ('discovery_scheduled', 'Discovery Scheduled'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], db_index=True, default='unreviewed', max_length=30)),
                ('application_status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('more_information_required', 'More Information Required'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('declined', 'Declined')], db_index=True, default='new', max_length=30)),
                ('payment_status', models.CharField(choices=[('not_invoiced', 'Not Invoiced'), ('invoice_draft', 'Invoice Draft'), ('invoice_sent', 'Invoice Sent'), ('payment_pending', 'Payment Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='not_invoiced', max_length=30)),
                ('booking_status', models.CharField(choices=[('not_booked', 'Not Booked'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('attended', 'Attended'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], db_index=True, default='not_booked', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profile', to='api.vendorlead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('lead_intake', 'Lead Intake'), ('discovery_call', 'Discovery Call'), ('qualification', 'Qualification'), ('application_review', 'Application Review'), ('payment', 'Payment'), ('market_preparation', 'Market Preparation'), ('post_market', 'Post-Market'), ('general', 'General')], max_length=30)),
                ('content', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.vendorprofile')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.vendorprofile'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emailtemplate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='api.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.vendorprofile'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('application_decision', 'Application Decision'), ('payment_recorded', 'Payment Recorded'), ('payment_reversed', 'Payment Reversed'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('hold_extended', 'Hold Extended'), ('inventory_adjusted', 'Inventory Adjusted'), ('booth_reassigned', 'Booth Reassigned'), ('authorization_override', 'Authorization Override')], max_length=50)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lead_registered', 'Lead Registered'), ('lead_imported', 'Lead Imported from CSV'), ('application_submitted', 'Application Submitted'), ('call_attempted', 'Call Attempted'), ('call_completed', 'Call Completed'), ('qualification_changed', 'Qualification Changed'), ('application_reviewed', 'Application Reviewed'), ('note_added', 'Note Added'), ('email_drafted', 'Email Drafted'), ('email_sent', 'Email Sent'), ('market_dates_shared', 'Market Dates Shared'), ('pricing_shared', 'Pricing Shared'), ('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('payment_reminder_sent', 'Payment Reminder Sent'), ('payment_recorded', 'Payment Recorded'), ('booking_confirmed', 'Booking Confirmed'), ('market_packet_sent', 'Market Packet Sent'), ('attendance_recorded', 'Attendance Recorded'), ('post_market_appreciation_sent', 'Post-Market Appreciation Sent')], db_index=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.vendorprofile')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryhold',
            index=models.Index(fields=['booth_variant', 'is_expired'], name='api_invento_booth_v_1a5ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='boothvariant',
            index=models.Index(fields=['market', 'is_active'], name='api_boothva_market__1b8b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['market', 'is_active'], name='api_addon_market__8d684f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', '-created_at'], name='api_payment_invoice_f67734_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['qualification_status', '-updated_at'], name='api_vendorp_qualifi_4ee93d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['payment_status', '-updated_at'], name='api_vendorp_payment_7633de_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['booking_status', '-updated_at'], name='api_vendorp_booking_cf94ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vendornote',
            index=models.Index(fields=['profile', '-created_at'], name='api_vendorn_profile_4cee44_idx'),
        ),
        migrations.AddIndex(
            model_name='vendornote',
            index=models.Index(fields=['note_type', '-created_at'], name='api_vendorn_note_ty_78b090_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['profile', 'status', 'due_date'], name='api_task_profile_d37308_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='api_task_assigne_07e67b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['profile', '-created_at'], name='api_invoice_profile_6328f0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-created_at'], name='api_invoice_status_0748d6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['market', 'status'], name='api_invoice_market__c55c49_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['profile', '-sent_at'], name='api_communi_profile_7470f2_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status', '-created_at'], name='api_communi_status_5f9014_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['market', 'status'], name='api_booking_market__5e7aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['profile', 'status'], name='api_booking_profile_9ff9f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'confirmed'])), fields=('profile', 'market'), name='unique_active_booking_per_market'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['profile', '-created_at'], name='api_auditlo_profile_870c60_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', '-created_at'], name='api_auditlo_event_t_7feffa_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['profile', '-created_at'], name='api_activit_profile_23383f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='api_activit_activit_09e732_idx'),
        ),
    ]
